///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
/*class ResponsePrimeGPT {

  String? id;
  String? object;
  int? created;
  String? model;
  List<ResponsePrimeGPTChoices>? choices;
  ResponsePrimeGPTUsage? usage;

  ResponsePrimeGPT({
    this.id,
    this.object,
    this.created,
    this.model,
    this.choices,
    this.usage,
  });
  ResponsePrimeGPT.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    object = json['object']?.toString();
    created = json['created']?.toInt();
    model = json['model']?.toString();
    if (json['choices'] != null) {
      final v = json['choices'];
      final arr0 = <ResponsePrimeGPTChoices>[];
      v.forEach((v) {
        arr0.add(ResponsePrimeGPTChoices.fromJson(v));
      });
      choices = arr0;
    }
    usage = (json['usage'] != null) ? ResponsePrimeGPTUsage.fromJson(json['usage']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['object'] = object;
    data['created'] = created;
    data['model'] = model;
    if (choices != null) {
      final v = choices;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['choices'] = arr0;
    }
    final usage = this.usage;
    if (usage != null) {
      data['usage'] = usage.toJson();
    }
    return data;
  }
}
class ResponsePrimeGPTChoices {
  int? index;
  ResponsePrimeGPTChoicesMessage? message;

  ResponsePrimeGPTChoices({
    this.index,
    this.message,
  });
  ResponsePrimeGPTChoices.fromJson(Map<String, dynamic> json) {
    index = json['index']?.toInt();
    message = (json['message'] != null) ? ResponsePrimeGPTChoicesMessage.fromJson(json['message']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['index'] = index;
    final message = this.message;
    if (message != null) {
      data['message'] = message.toJson();
    }
    return data;
  }
}
class ResponsePrimeGPTChoicesMessage {

  String? role;
  String? content;

  ResponsePrimeGPTChoicesMessage({
    this.role,
    this.content,
  });
  ResponsePrimeGPTChoicesMessage.fromJson(Map<String, dynamic> json) {
    role = json['role']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['role'] = role;
    data['content'] = content;
    return data;
  }
}
class ResponsePrimeGPTUsage {

  int? promptTokens;
  int? completionTokens;
  int? totalTokens;

  ResponsePrimeGPTUsage({
    this.promptTokens,
    this.completionTokens,
    this.totalTokens,
  });
  ResponsePrimeGPTUsage.fromJson(Map<String, dynamic> json) {
    promptTokens = json['prompt_tokens']?.toInt();
    completionTokens = json['completion_tokens']?.toInt();
    totalTokens = json['total_tokens']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['prompt_tokens'] = promptTokens;
    data['completion_tokens'] = completionTokens;
    data['total_tokens'] = totalTokens;
    return data;
  }
}*/

class ResponsePrimeGPT {
  String? object;
  List<Data>? data;
  bool? hasMore;

  ResponsePrimeGPT({this.object, this.data, this.hasMore});

  ResponsePrimeGPT.fromJson(Map<String, dynamic> json) {
    object = json['object'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
    hasMore = json['has_more'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['object'] = object;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['has_more'] = hasMore;
    return data;
  }
}

class Data {
  String? object;
  String? id;
  int? createdAt;
  String? level;
  String? message;
  Null data;
  String? type;

  Data(
      {this.object,
        this.id,
        this.createdAt,
        this.level,
        this.message,
        this.data,
        this.type});

  Data.fromJson(Map<String, dynamic> json) {
    object = json['object'];
    id = json['id'];
    createdAt = json['created_at'];
    level = json['level'];
    message = json['message'];
    data = json['data'];
    type = json['type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['object'] = object;
    data['id'] = id;
    data['created_at'] = createdAt;
    data['level'] = level;
    data['message'] = message;
    data['data'] = this.data;
    data['type'] = type;
    return data;
  }
}



